Companies We Worked With List
Muddoo/All_Correct pull request #10
Opened 2021-09-27 23:22 UTC by sayus2884

2021-09-27 23:27 UTC, sayus2884 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Companies We Work With Section](https://trello.com/c/IDFxZR9B/18-companies-we-work-with-section)

2021-09-28 01:16 UTC, hulyak commented
this looks very good, @sayus2884.

2021-09-28 22:37 UTC, hulyak approved these changes

2021-10-01 12:21 UTC, Muddoo requested changes
check the hints i posted in slack and apply it
thank you

2021-10-03 20:50 UTC, closed without merging